-- ============================================================================
-- AgroGuard IA — Schema do Banco de Dados (Sprint 3-4 / v2)
-- ----------------------------------------------------------------------------
-- PostgreSQL 16. Modela a persistência da telemetria coletada no campo (via
-- dataset OU via API autenticada), os sinistros históricos, os scores de risco
-- gerados pelo motor de ML, os alertas derivados, as leituras rejeitadas na
-- validação e a trilha de auditoria de uso da API.
--
-- Aplicado AUTOMATICAMENTE pelo docker-compose na 1ª subida do container
-- (montado em /docker-entrypoint-initdb.d/). Para aplicar manualmente:
--   psql "$DATABASE_URL" -f sql/schema.sql
--   ou:  python -m agroguard.db --aplicar-schema
--
-- Modelo relacional (3FN):
--   equipamentos    1 ─── N  leituras_telemetria
--   leituras_telemetria 1 ─ 1  scores_risco   (score gerado pelo modelo)
--   leituras_telemetria 1 ─ 0/1 sinistros      (rótulo histórico do evento)
--   scores_risco    1 ─ 0/1 alertas            (alerta derivado do score)
--   leituras_rejeitadas e logs_uso não referenciam leituras (trilha independente,
--   sobrevive mesmo quando a leitura é recusada antes de existir).
-- ============================================================================

-- Idempotência: permite re-rodar o script em dev sem erro.
DROP VIEW  IF EXISTS vw_risco_completo;
DROP TABLE IF EXISTS logs_uso            CASCADE;
DROP TABLE IF EXISTS leituras_rejeitadas CASCADE;
DROP TABLE IF EXISTS alertas             CASCADE;
DROP TABLE IF EXISTS scores_risco        CASCADE;
DROP TABLE IF EXISTS sinistros           CASCADE;
DROP TABLE IF EXISTS leituras_telemetria CASCADE;
DROP TABLE IF EXISTS equipamentos        CASCADE;

-- ----------------------------------------------------------------------------
-- 1) Frota de equipamentos (dimensão)
-- ----------------------------------------------------------------------------
CREATE TABLE equipamentos (
    equip_id                VARCHAR(10) PRIMARY KEY,             -- ex.: 'EQ-014'
    tipo_equip              VARCHAR(20) NOT NULL,                -- Colheitadeira | Trator | Pulverizador | Caminhão
    idade_equipamento_anos  SMALLINT NOT NULL CHECK (idade_equipamento_anos BETWEEN 0 AND 60),
    fazenda                 VARCHAR(40) NOT NULL DEFAULT 'FAZ-01',
    regiao                  VARCHAR(40) NOT NULL DEFAULT 'Sorriso-MT',
    CONSTRAINT chk_tipo_equip CHECK (
        tipo_equip IN ('Colheitadeira', 'Trator', 'Pulverizador', 'Caminhão')
    )
);

COMMENT ON TABLE  equipamentos IS 'Cadastro da frota — uma linha por equipamento.';
COMMENT ON COLUMN equipamentos.equip_id IS 'Identificador único do equipamento (EQ-XXX).';
COMMENT ON COLUMN equipamentos.fazenda  IS 'Fazenda onde o equipamento opera (agrupamento operacional).';
COMMENT ON COLUMN equipamentos.regiao   IS 'Região geográfica do equipamento (agrupamento analítico).';

-- ----------------------------------------------------------------------------
-- 2) Leituras de telemetria + contexto ambiental/operacional (fato)
-- ----------------------------------------------------------------------------
CREATE TABLE leituras_telemetria (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equip_id                    VARCHAR(10) NOT NULL REFERENCES equipamentos(equip_id),
    data_hora                   TIMESTAMP   NOT NULL,

    -- Geolocalização (GPS embarcado)
    latitude                    DOUBLE PRECISION NOT NULL,
    longitude                   DOUBLE PRECISION NOT NULL,

    -- Telemetria do equipamento (IoT)
    velocidade_kmh              NUMERIC(6,1)  NOT NULL,
    inclinacao_graus            NUMERIC(5,1)  NOT NULL,
    vibracao_g                  NUMERIC(5,2)  NOT NULL,

    -- Variáveis climáticas / ambientais (API de clima + bases públicas)
    precip_24h_mm               NUMERIC(6,1)  NOT NULL,
    precip_prev_6h_mm           NUMERIC(6,1)  NOT NULL,
    umidade_solo                NUMERIC(4,2)  NOT NULL CHECK (umidade_solo BETWEEN 0 AND 1),
    vento_max_kmh                NUMERIC(6,1)  NOT NULL,

    -- Geografia / topografia (MapBiomas/ANA + SRTM/EMBRAPA)
    dist_corpo_dagua_m          INTEGER       NOT NULL CHECK (dist_corpo_dagua_m >= 0),
    declividade_pct             NUMERIC(5,2)  NOT NULL,

    -- Contexto operacional
    tipo_operacao               VARCHAR(15)   NOT NULL,          -- campo | transporte | parado
    turno                       VARCHAR(10)   NOT NULL,          -- manha | tarde | noite
    jornada_acumulada_h         NUMERIC(5,1)  NOT NULL,
    dias_desde_manutencao       SMALLINT      NOT NULL,
    experiencia_operador_anos   SMALLINT      NOT NULL,

    -- Rastreabilidade da entrada (Sprint 3/4: backend integrador)
    origem                      VARCHAR(20)   NOT NULL DEFAULT 'dataset',
    recebido_em                 TIMESTAMP     NOT NULL DEFAULT now(),
    payload_hash                CHAR(64),                        -- sha256 do payload canônico (dedup/integridade)
    payload_bruto                JSONB,                           -- payload original recebido pela API (auditoria)
    request_id                  UUID,                             -- correlaciona com logs_uso/auditoria

    CONSTRAINT chk_tipo_operacao CHECK (tipo_operacao IN ('campo', 'transporte', 'parado')),
    CONSTRAINT chk_turno         CHECK (turno IN ('manha', 'tarde', 'noite')),
    CONSTRAINT chk_origem        CHECK (origem IN ('dataset', 'api', 'simulador')),
    CONSTRAINT uq_leitura_equip_datahora UNIQUE (equip_id, data_hora)
);

COMMENT ON TABLE leituras_telemetria IS
    'Leitura instantânea de um equipamento: telemetria IoT + enriquecimento ambiental/operacional.';
COMMENT ON COLUMN leituras_telemetria.origem IS 'De onde a leitura chegou: dataset (carga inicial) | api | simulador.';
COMMENT ON COLUMN leituras_telemetria.payload_hash IS 'sha256 do payload canônico — usado para detectar duplicatas.';

-- Índices para as consultas de risco mais frequentes (ranking, histórico, mapa)
CREATE INDEX idx_leituras_equip       ON leituras_telemetria (equip_id);
CREATE INDEX idx_leituras_data_hora   ON leituras_telemetria (data_hora);
CREATE INDEX idx_leituras_dist_agua   ON leituras_telemetria (dist_corpo_dagua_m);
CREATE INDEX idx_leituras_request_id  ON leituras_telemetria (request_id);

-- ----------------------------------------------------------------------------
-- 3) Scores de risco gerados pelo modelo de ML (fato derivado)
-- ----------------------------------------------------------------------------
CREATE TABLE scores_risco (
    id                  BIGSERIAL PRIMARY KEY,
    leitura_id          BIGINT NOT NULL REFERENCES leituras_telemetria(id) ON DELETE CASCADE,
    risco_score         SMALLINT NOT NULL CHECK (risco_score BETWEEN 0 AND 100),
    classe_risco        VARCHAR(10) NOT NULL,                        -- Baixo | Medio | Alto | Critico
    alerta              BOOLEAN NOT NULL DEFAULT FALSE,              -- TRUE quando score >= limiar (80)
    fatores_principais  JSONB NOT NULL DEFAULT '[]',                 -- explicabilidade (preenchida por ml/explicabilidade)
    regras_aplicadas    JSONB NOT NULL DEFAULT '[]',                 -- regras de negócio que dispararam
    recomendacoes       JSONB NOT NULL DEFAULT '[]',                 -- ações sugeridas (alertas.servico.recomendar)
    request_id          UUID,                                        -- correlaciona com logs_uso/auditoria
    latencia_ms         INTEGER,                                     -- tempo de inferência (observabilidade)
    modelo_versao       VARCHAR(20) NOT NULL DEFAULT 'v0.3',
    gerado_em           TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT chk_classe_risco CHECK (classe_risco IN ('Baixo', 'Medio', 'Alto', 'Critico')),
    CONSTRAINT uq_score_por_leitura UNIQUE (leitura_id, modelo_versao)
);

COMMENT ON TABLE scores_risco IS
    'Score de risco (0–100) e classe previstos pelo modelo para cada leitura. alerta=TRUE dispara notificação.';

CREATE INDEX idx_scores_leitura  ON scores_risco (leitura_id);
CREATE INDEX idx_scores_classe   ON scores_risco (classe_risco);
CREATE INDEX idx_scores_alerta   ON scores_risco (alerta) WHERE alerta IS TRUE;

-- ----------------------------------------------------------------------------
-- 4) Sinistros históricos (rótulo / ground-truth)
-- ----------------------------------------------------------------------------
CREATE TABLE sinistros (
    id                  BIGSERIAL PRIMARY KEY,
    leitura_id          BIGINT NOT NULL REFERENCES leituras_telemetria(id) ON DELETE CASCADE,
    ocorreu             BOOLEAN NOT NULL,                        -- houve sinistro nesta leitura?
    tipo_sinistro       VARCHAR(15),                            -- atolamento|colisao|tombamento|mecanico (NULL se não ocorreu)
    severidade_sinistro VARCHAR(15),                            -- leve|moderado|grave|perda_total
    CONSTRAINT uq_sinistro_por_leitura UNIQUE (leitura_id)
);

COMMENT ON TABLE sinistros IS
    'Registro histórico de sinistro associado a uma leitura (usado como rótulo de treino e validação).';

CREATE INDEX idx_sinistros_leitura ON sinistros (leitura_id);
CREATE INDEX idx_sinistros_ocorreu ON sinistros (ocorreu);

-- ----------------------------------------------------------------------------
-- 5) Alertas — derivados de um score de risco que ultrapassa o critério
-- ----------------------------------------------------------------------------
CREATE TABLE alertas (
    id             BIGSERIAL PRIMARY KEY,
    score_id       BIGINT UNIQUE REFERENCES scores_risco(id) ON DELETE CASCADE,
    leitura_id     BIGINT REFERENCES leituras_telemetria(id) ON DELETE CASCADE,
    equip_id       VARCHAR(10) NOT NULL,
    nivel          VARCHAR(10) NOT NULL,                          -- Alto | Critico
    criterio       TEXT NOT NULL,                                 -- critério explícito que disparou o alerta
    mensagem       TEXT NOT NULL,                                 -- mensagem em pt-BR para o operador/gestor
    recomendacoes  JSONB NOT NULL DEFAULT '[]',
    status         VARCHAR(12) NOT NULL DEFAULT 'aberto',         -- aberto | reconhecido
    request_id     UUID,
    criado_em      TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_alerta_nivel  CHECK (nivel IN ('Alto', 'Critico')),
    CONSTRAINT chk_alerta_status CHECK (status IN ('aberto', 'reconhecido'))
);

COMMENT ON TABLE alertas IS
    'Alerta preventivo derivado de um score de risco acima do critério — rastreável até a leitura de origem.';

CREATE INDEX idx_alertas_equip_criado ON alertas (equip_id, criado_em);
CREATE INDEX idx_alertas_status       ON alertas (status);

-- ----------------------------------------------------------------------------
-- 6) Leituras rejeitadas — trilha de tudo que a validação recusou
-- ----------------------------------------------------------------------------
CREATE TABLE leituras_rejeitadas (
    id            BIGSERIAL PRIMARY KEY,
    recebido_em   TIMESTAMP DEFAULT now(),
    origem        VARCHAR(20),
    codigo        VARCHAR(20) NOT NULL,                          -- validacao|duplicado|equip_desconhecido|assinatura|inconsistencia
    motivo        TEXT NOT NULL,
    payload       JSONB,
    payload_hash  CHAR(64),
    request_id    UUID,
    CONSTRAINT chk_rejeitada_codigo CHECK (
        codigo IN ('validacao', 'duplicado', 'equip_desconhecido', 'assinatura', 'inconsistencia')
    )
);

COMMENT ON TABLE leituras_rejeitadas IS
    'Toda leitura recusada pela API — rastreabilidade de entradas inválidas (Sprint 4).';

CREATE INDEX idx_rejeitadas_codigo ON leituras_rejeitadas (codigo);
CREATE INDEX idx_rejeitadas_request_id ON leituras_rejeitadas (request_id);

-- ----------------------------------------------------------------------------
-- 7) Logs de uso — uma linha por requisição HTTP (auditoria / rastreabilidade)
-- ----------------------------------------------------------------------------
CREATE TABLE logs_uso (
    id            BIGSERIAL PRIMARY KEY,
    request_id    UUID NOT NULL,
    ocorrido_em   TIMESTAMP DEFAULT now(),
    kid           VARCHAR(20),
    papel         VARCHAR(15),
    metodo        VARCHAR(8),
    rota          TEXT,
    status_http   SMALLINT,
    duracao_ms    INTEGER,
    ip            VARCHAR(45),
    detalhe       JSONB
);

COMMENT ON TABLE logs_uso IS
    'Registro de uso da API — uma linha por requisição, correlacionável por request_id (Sprint 3: segurança/registros de uso).';

CREATE INDEX idx_logs_uso_request_id  ON logs_uso (request_id);
CREATE INDEX idx_logs_uso_ocorrido_em ON logs_uso (ocorrido_em);

-- ----------------------------------------------------------------------------
-- 8) View de conveniência: leitura + score + sinistro (1 linha por leitura)
--    Simplifica o dashboard e as queries analíticas.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_risco_completo AS
SELECT DISTINCT ON (l.id)
    l.id,
    l.equip_id,
    e.tipo_equip,
    e.idade_equipamento_anos,
    e.fazenda,
    e.regiao,
    l.data_hora,
    l.latitude,
    l.longitude,
    l.velocidade_kmh,
    l.vibracao_g,
    l.precip_24h_mm,
    l.umidade_solo,
    l.dist_corpo_dagua_m,
    l.declividade_pct,
    l.tipo_operacao,
    l.turno,
    l.jornada_acumulada_h,
    l.dias_desde_manutencao,
    s.risco_score,
    s.classe_risco,
    s.alerta,
    s.fatores_principais,
    s.recomendacoes,
    s.modelo_versao,
    COALESCE(si.ocorreu, FALSE) AS sinistro,
    si.tipo_sinistro,
    si.severidade_sinistro
FROM leituras_telemetria l
JOIN equipamentos e        ON e.equip_id = l.equip_id
LEFT JOIN scores_risco s   ON s.leitura_id = l.id
LEFT JOIN sinistros si     ON si.leitura_id = l.id
ORDER BY l.id, s.gerado_em DESC NULLS LAST;

COMMENT ON VIEW vw_risco_completo IS
    'Visão consolidada (leitura + score mais recente do modelo + sinistro) — base do dashboard e das análises.';
